# Generated by Django 4.1 on 2024-02-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="nothing",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="title",
            field=models.CharField(default="houhouhou", max_length=32),
        ),
    ]
