# Generated by Django 4.1 on 2024-02-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0002_userinfo_nothing_userinfo_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="onlyTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=16)),
            ],
        ),
    ]
